name: dynamic_color
description: Flutter package to obtain dynamic colors on Android S+ and create harmonized color schemes.
version: 1.0.1
repository: https://github.com/material-foundation/material-dynamic-color-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.6.0-0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  material_color_utilities: ^0.1.4

dev_dependencies:
  flutter_lints: ^1.0.0
  meta: ^1.3.0

flutter:
  plugin:
    platforms:
      android:
        package: io.material.plugins.dynamic_color
        pluginClass: DynamicColorPlugin
